/**
 * World type configs. Canon: docs/03_map/World_Types_and_Terrain_Distribution_Spec.md
 * landThreshold: higher threshold => less land (when using noise > threshold)
 */
import type { WorldConfig, WorldTypeId } from "./types.js";

export function getWorldConfig(worldType: WorldTypeId): WorldConfig {
  const configs: Record<WorldTypeId, WorldConfig> = {
    BALANCED: {
      worldType: "BALANCED",
      landThreshold: [0.4, 0.55], // higher threshold => less land; 45–60% land
      noiseFrequency: [0.04, 0.08],
      edgeFalloffWidth: 8,
      edgeFalloffStrength: 0.15,
      landmaskSmoothIterations: 1,
      landmaskSmoothMajority: 4,
      continentRange: [4, 6],
      minContinentSize: 200,
      islandRange: [5, 10],
      minIslandSize: 8,
      minLakeSize: 6,
      terrainRatios: { plain: 0.45, forest: 0.25, mountain: 0.15, desert: 0.15 },
      thresholdDeltas: { mountain: 0, forest: 0, desert: 0 },
      riverCount: [3, 8],
      riverLength: [5, 20],
      resourceDensityNormal: 0.25,
      resourceDensityDesert: 0.12,
      moneyScienceRatio: 0.5,
      cityRange: [50, 100],
    },
    CONTINENTAL: {
      worldType: "CONTINENTAL",
      landThreshold: [0.3, 0.5], // higher threshold => less land; 60–75% land
      noiseFrequency: [0.03, 0.05],
      edgeFalloffWidth: 5,
      edgeFalloffStrength: 0.12,
      landmaskSmoothIterations: 1,
      landmaskSmoothMajority: 4,
      continentRange: [3, 4],
      minContinentSize: 400,
      islandRange: [3, 6],
      minIslandSize: 12,
      minLakeSize: 10,
      terrainRatios: { plain: 0.5, forest: 0.22, mountain: 0.15, desert: 0.13 },
      thresholdDeltas: { mountain: 0, forest: 0.04, desert: -0.03 },
      riverCount: [5, 10],
      riverLength: [8, 20],
      resourceDensityNormal: 0.23,
      resourceDensityDesert: 0.1,
      moneyScienceRatio: 0.55,
      cityRange: [60, 100],
    },
    ARCHIPELAGO: {
      worldType: "ARCHIPELAGO",
      landThreshold: [0.45, 0.6], // higher threshold => less land; 30–45% land (55–70% water)
      noiseFrequency: [0.06, 0.1],
      edgeFalloffWidth: 4,
      edgeFalloffStrength: 0.25,
      landmaskSmoothIterations: 0,
      landmaskSmoothMajority: 4,
      continentRange: [2, 3],
      minContinentSize: 150,
      islandRange: [8, 15],
      minIslandSize: 6,
      minLakeSize: 4,
      terrainRatios: { plain: 0.4, forest: 0.3, mountain: 0.12, desert: 0.18 },
      thresholdDeltas: { mountain: -0.03, forest: 0.05, desert: 0.03 },
      riverCount: [2, 5],
      riverLength: [3, 12],
      resourceDensityNormal: 0.28,
      resourceDensityDesert: 0.15,
      moneyScienceRatio: 0.5,
      cityRange: [50, 80],
    },
    PANGAEA: {
      worldType: "PANGAEA",
      landThreshold: [0.2, 0.4], // higher threshold => less land; 60–70% land
      noiseFrequency: [0.02, 0.04],
      edgeFalloffWidth: 10,
      edgeFalloffStrength: 0.06,
      landmaskSmoothIterations: 0,
      landmaskSmoothMajority: 4,
      continentRange: [1, 1],
      minContinentSize: 2000,
      islandRange: [5, 10],
      minIslandSize: 5,
      minLakeSize: 8,
      terrainRatios: { plain: 0.48, forest: 0.23, mountain: 0.16, desert: 0.13 },
      thresholdDeltas: { mountain: 0.01, forest: -0.02, desert: -0.02 },
      riverCount: [6, 10],
      riverLength: [10, 20],
      resourceDensityNormal: 0.22,
      resourceDensityDesert: 0.1,
      moneyScienceRatio: 0.5,
      cityRange: [70, 100],
    },
    WILD: {
      worldType: "WILD",
      landThreshold: [0.35, 0.65],
      noiseFrequency: [0.03, 0.12],
      edgeFalloffWidth: 8,
      continentRange: [2, 6],
      minContinentSize: 100,
      islandRange: [5, 15],
      minIslandSize: 5,
      minLakeSize: 4,
      terrainRatios: { plain: 0.4, forest: 0.25, mountain: 0.15, desert: 0.2 },
      thresholdDeltas: { mountain: 0, forest: 0, desert: 0 },
      riverCount: [3, 12],
      riverLength: [3, 20],
      resourceDensityNormal: 0.25,
      resourceDensityDesert: 0.12,
      moneyScienceRatio: 0.5,
      cityRange: [50, 100],
    },
  };
  return configs[worldType];
}
